spring:
    output:
        ansi:
            enabled: always
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/parking_control_db
        username: root
        password: 1234567890