spring:
    output:
        ansi:
            enabled: always
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: jdbc:mysql://localhost:3306/parking_control_db
        username: root
        password: 1234567890